# Generated by Django 5.1.4 on 2024-12-23 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField()),
                ('bilan_prescrit', models.CharField(choices=[('bilan biologique', 'Bilan Biologique'), ('bilan radiologique', 'Bilan Radiologique'), ('bilan biologique et radiologique', 'Bilan Biologique et Radiologique'), ('Aucun bilan', 'Aucun Bilan')], default='Aucun bilan', max_length=50)),
                ('resume', models.TextField(blank=True, null=True)),
                ('dossier_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.dossierpatient')),
            ],
            options={
                'db_table': 'consultation',
            },
        ),
    ]
