# Generated by Django 5.1.4 on 2024-12-24 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0003_alter_consultation_bilan_prescrit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_etat_patient', models.TextField()),
                ('medicament_pris', models.BooleanField(default=False)),
                ('description_soins', models.TextField()),
                ('date_soin', models.DateTimeField()),
                ('dossier_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.dossierpatient')),
                ('infirmier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='backendapp.infirmier')),
            ],
            options={
                'db_table': 'soins',
            },
        ),
    ]
