# Generated by Django 5.1.4 on 2024-12-25 09:36

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0004_soins'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='numero_consultation',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='bilan_prescrit',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('bilan biologique', 'Bilan Biologique'), ('bilan radiologique', 'Bilan Radiologique'), ('Aucun bilan', 'Aucun Bilan')], max_length=47),
        ),
    ]
