# Generated by Django 5.1.4 on 2024-12-25 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0006_alter_consultation_numero_consultation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation', models.ForeignKey(db_column='consultation_id', on_delete=django.db.models.deletion.CASCADE, to='backendapp.consultation')),
                ('dossier_patient', models.ForeignKey(db_column='dossier_patient_id', on_delete=django.db.models.deletion.CASCADE, to='backendapp.dossierpatient')),
            ],
            options={
                'db_table': 'ordonnance',
            },
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('dose', models.CharField(max_length=255)),
                ('duree', models.CharField(db_column='durée', max_length=255)),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='backendapp.ordonnance')),
            ],
            options={
                'db_table': 'medicament',
            },
        ),
    ]
