# Generated by Django 5.1.4 on 2024-12-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0008_bilanbiologique_bilanradiologique'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='telephone_urgence',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
