# Generated by Django 5.1.4 on 2024-12-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0012_bilanradiologique_numero_consultation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilanbiologique',
            name='resultat_analyse',
        ),
        migrations.RemoveField(
            model_name='bilanbiologique',
            name='resultat_examen_imagerie',
        ),
        migrations.AddField(
            model_name='bilanbiologique',
            name='numero_consultation',
            field=models.IntegerField(default=1),
        ),
    ]
