# Generated by Django 5.1.4 on 2024-12-31 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0013_remove_bilanbiologique_resultat_analyse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='medecinConsultant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backendapp.medecin'),
        ),
    ]
