# Generated by Django 5.1.4 on 2025-01-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0014_consultation_medecinconsultant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='telephone_urgence',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
