# Generated by Django 5.1.4 on 2025-01-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0015_alter_patient_telephone_urgence'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20),
        ),
    ]
