# Generated by Django 5.1.4 on 2024-12-07 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGL_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medecin_traitant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='IGL_App.staff'),
        ),
        migrations.CreateModel(
            name='DossierPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_qr', models.CharField(max_length=255)),
                ('etat', models.CharField(max_length=20)),
                ('antecedents', models.TextField()),
                ('medecin_traitant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_patient', to='IGL_App.staff')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IGL_App.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField()),
                ('bilan_prescrit', models.TextField()),
                ('resume', models.TextField()),
                ('dossier_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IGL_App.dossierpatient')),
            ],
        ),
        migrations.CreateModel(
            name='BilanRadiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_rendu', models.TextField()),
                ('images', models.BinaryField()),
                ('date_examen', models.DateTimeField()),
                ('radiologue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bilans_radiologiques', to='IGL_App.staff')),
                ('dossier_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IGL_App.dossierpatient')),
            ],
        ),
        migrations.CreateModel(
            name='BilanBiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat_analyse', models.TextField()),
                ('resultat_examen_imagerie', models.TextField()),
                ('date_examen', models.DateTimeField()),
                ('graphe', models.BinaryField()),
                ('laborantin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bilans_biologiques', to='IGL_App.staff')),
                ('dossier_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IGL_App.dossierpatient')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.TextField()),
                ('quantite', models.IntegerField()),
                ('duree', models.CharField(max_length=255)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IGL_App.consultation')),
                ('dossier_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IGL_App.dossierpatient')),
            ],
        ),
        migrations.CreateModel(
            name='Soins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_etat_patient', models.TextField()),
                ('medicament_pris', models.BooleanField(default=False)),
                ('description_soins', models.TextField()),
                ('date_soin', models.DateTimeField()),
                ('dossier_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IGL_App.dossierpatient')),
                ('infirmier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins', to='IGL_App.staff')),
            ],
        ),
    ]
