# Generated by Django 5.1.4 on 2024-12-07 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IGL_App', '0003_alter_staff_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staff',
            table='Staff',
        ),
    ]
