# Generated by Django 5.1.4 on 2024-12-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IGL_App', '0004_alter_staff_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'managed': True},
        ),
    ]
