# Generated by Django 5.1.4 on 2024-12-09 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IGL_App', '0005_alter_staff_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staff',
            table='IGL_App_staff',
        ),
    ]
