# Generated by Django 5.1.4 on 2024-12-09 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IGL_App', '0006_alter_staff_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staff',
            table='Staff',
        ),
    ]
