# Generated by Django 5.1.4 on 2024-12-09 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGL_App', '0008_alter_patient_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dossierpatient',
            old_name='antecedents',
            new_name='antécédents',
        ),
        migrations.AlterField(
            model_name='patient',
            name='medecin_traitant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IGL_App.staff'),
        ),
        migrations.AlterModelTable(
            name='dossierpatient',
            table='Dossier_patient',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='Patient',
        ),
    ]
