# Generated by Django 5.1.4 on 2024-12-10 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGL_App', '0009_rename_antecedents_dossierpatient_antécédents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossierpatient',
            name='medecin_traitant',
        ),
        migrations.AddField(
            model_name='patient',
            name='mot_de_passe',
            field=models.CharField(default='pbkdf2_sha256$870000$u3aztIJ5L14ktfzQbq8vyp$x2fFhVrRhM5sIUajarPxbPHqqQ509l1n+smWXoRGaDE=', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medecin_traitant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IGL_App.staff'),
        ),
    ]
