# Generated by Django 5.1.3 on 2024-12-12 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGL_App', '0010_remove_dossierpatient_medecin_traitant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='bilan_prescrit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mot_de_passe',
            field=models.CharField(default='pbkdf2_sha256$870000$FeLp1hu3ThGuvIdk1WrpoG$F8sCIt1rHSSzcdF+5DvOAMqAoTUdKxLZCbnSSuk8hfc=', max_length=255),
        ),
        migrations.AlterField(
            model_name='soins',
            name='infirmier',
            field=models.ForeignKey(limit_choices_to={'role': 'infirmier'}, on_delete=django.db.models.deletion.CASCADE, to='IGL_App.staff'),
        ),
        migrations.AlterModelTable(
            name='consultation',
            table='Consultation',
        ),
        migrations.AlterModelTable(
            name='soins',
            table='Soins',
        ),
    ]
