# Generated by Django 5.1.3 on 2024-12-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGL_App', '0011_alter_consultation_bilan_prescrit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mot_de_passe',
            field=models.CharField(default='pbkdf2_sha256$870000$J8ZWqtXItgHAQWGU1MBN23$LPXWAh1KlMpXQ0ugWINdLnCAShnSiRru0v/KWeKQTxA=', max_length=255),
        ),
    ]
