# Generated by Django 5.1.3 on 2024-12-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGL_App', '0013_drop_unused_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mot_de_passe',
            field=models.CharField(default='pbkdf2_sha256$870000$DAvCMOYXRMB2H1WjWQ7MuN$p/wzAVwPLrfujfk8DGM+QJ/G97Ujbs12Ff/b2hi1GRk=', max_length=255),
        ),
    ]
