# Generated by Django 5.1.3 on 2024-12-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGL_App', '0014_alter_patient_mot_de_passe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mot_de_passe',
            field=models.CharField(default='pbkdf2_sha256$870000$nw1LCQmG9XkzkYSFXglb2r$UNzIJTce9zPegFjLbcxXRx9no1BOQw9Kc1t0BWqnVnk=', max_length=255),
        ),
    ]
