# Generated by Django 5.1.4 on 2024-12-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGL_App', '0016_alter_patient_mot_de_passe'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='numero_consultation',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mot_de_passe',
            field=models.CharField(default='pbkdf2_sha256$870000$xhFEQ2AgLyTtYt6zIMeMqv$jcwIbXGrkppC7CI9S8gRIb2+14O2HumI5QtupG10uNI=', max_length=255),
        ),
    ]
