# Generated by Django 5.1.4 on 2024-12-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGL_App', '0017_consultation_numero_consultation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mot_de_passe',
            field=models.CharField(default='pbkdf2_sha256$870000$TGD6RsOdPmiRcuIyEEjTm5$2oDnGpsmGhe60vEA81DAZkFUo75SRw111/+GbWKA4Hc=', max_length=255),
        ),
    ]
