# Generated by Django 5.1.4 on 2024-12-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGL_App', '0018_alter_patient_mot_de_passe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='numero_consultation',
        ),
        migrations.AlterField(
            model_name='patient',
            name='mot_de_passe',
            field=models.CharField(default='pbkdf2_sha256$870000$hIRzPZnEgSqReYKxdeZSSK$MlBcTA2zmB+iNKDHg7y9Q4CgWnwTXDZ5ihaS8EkYsRE=', max_length=255),
        ),
    ]
