# Generated by Django 5.1.4 on 2024-12-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGL_App', '0019_remove_consultation_numero_consultation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mot_de_passe',
            field=models.CharField(default='pbkdf2_sha256$870000$bJnFLgds1uqCLaGtf1iuO9$Uib56cuvy3exTCLuC1jUTMZDbGDAz65J4HjCa6bvvm4=', max_length=255),
        ),
    ]
