# Generated by Django 5.1.3 on 2024-12-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGL_App', '0021_alter_patient_mot_de_passe'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='numero_consultation',
            field=models.IntegerField( unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mot_de_passe',
            field=models.CharField(default='pbkdf2_sha256$870000$2r3C9zE0f6jYfSwJ9VVC5V$rOCGq7/aoCRokbA9pNT4dS7ibxFrwcQHcyNythpFU5I=', max_length=255),
        ),
    ]
