# Generated by Django 5.1.3 on 2024-12-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGL_App', '0022_consultation_numero_consultation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mot_de_passe',
            field=models.CharField(default='pbkdf2_sha256$870000$rOP3nnbw9gN0blh3BjrpK2$vsDd4xbGmT6PeVJBX7kU++wZlKj2xHztnnb39uDeG5k=', max_length=255),
        ),
    ]
