# Generated by Django 5.1.3 on 2024-12-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGL_App', '0024_alter_consultation_numero_consultation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mot_de_passe',
            field=models.CharField(default='pbkdf2_sha256$870000$PJ8QGGA7QyvqzAW6gsaOGY$1XKPsVkzzIs5XUogqSF+qfAQOglZeEYCO8bMAqOVuaY=', max_length=255),
        ),
    ]
