# Generated by Django 5.1.4 on 2024-12-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGL_App', '0025_alter_patient_mot_de_passe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='bilan_prescrit',
            field=models.CharField(choices=[('bilan biologique', 'Bilan Biologique'), ('bilan radiologique', 'Bilan Radiologique'), ('bilan biologique et radiologique', 'Bilan Biologique et Radiologique'), ('Aucun bilan', 'Aucun Bilan')], default='Aucun bilan', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mot_de_passe',
            field=models.CharField(default='pbkdf2_sha256$870000$hsJHDQwmQ2pncCgQDcZJ8H$RDy1df650CJsikKBaWlky0f3OgA76jw2ym7SaqwVHf8=', max_length=255),
        ),
        migrations.AlterModelTable(
            name='ordonnance',
            table='Ordonnance',
        ),
    ]
